# Author: Karl Eriksson, Nasit Vurgun
services:
  django_server:
    build:
      context: ./stock_project
    container_name: django_server
    ports:
      - "8000:8000"
    networks:
      - stock_project_network
    environment:
      - ALLOWED_HOSTS=127.0.0.1,172.18.0.1,*
      - DEBUG=1

  macd_pipeline:
    build:
      context: ./ml_pipelines/macd_pipeline
    container_name: macd_pipeline
    depends_on:
      - django_server
    networks:
      - stock_project_network
    volumes:
      - shared_data:/app/shared_data
    command: /bin/sh -c "python main_script.py"

  ema_pipeline:
    build:
      context: ./ml_pipelines/ema_pipeline
    container_name: ema_pipeline
    depends_on:
      - django_server
    networks:
      - stock_project_network
    volumes:
      - shared_data:/app/shared_data
    command: /bin/sh -c "sleep 45 && python main_script.py"

  rsi_pipeline:
    build:
      context: ./ml_pipelines/rsi_pipeline
    container_name: rsi_pipeline
    depends_on:
      - django_server
    networks:
      - stock_project_network
    volumes:
      - shared_data:/app/shared_data
    command: /bin/sh -c "sleep 90 && python main_script.py"

  model_implementation:
    build:
      context: ./ml_pipelines/model_implementation
    container_name: model_implementation
    depends_on:
      - django_server
    networks:
      - stock_project_network
    volumes:
      - shared_data:/app/shared_data
    command: /bin/sh -c "sleep 135 && 
                  python main_script.py macd && 
                  python main_script.py rsi && 
                  python main_script.py ema"

networks:
  stock_project_network:

volumes:
  shared_data:
