apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-server
  template:
    metadata:
      labels:
        app: django-server
    spec:
      containers:
      - name: group2-django-server
        image: gcr.io/adroit-arcana-443708-m9/django_server:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: sqlite-volume
          mountPath: /app/db
      volumes:
      - name: sqlite-volume
        persistentVolumeClaim:
          claimName: sqlite-pvc
