apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-server
  template:
    metadata:
      labels:
        app: django-server
    spec:
      containers:
      - name: group2-django-server
        image: gcr.io/adroit-arcana-443708-m9/group2-django_server:v1
        ports:
        - containerPort: 8000
