# Author: Karl Eriksson, Isaac Lindegren Ternbom
apiVersion: batch/v1
kind: Job
metadata:
  name: ema-pipeline-job
spec:
  template:
    spec:
      containers:
      - name: ema-pipeline
        image: gcr.io/adroit-arcana-443708-m9/ema_pipeline:v1
        imagePullPolicy: Always
        command: ["python", "main_script.py"]  
      restartPolicy: Never
