apiVersion: v1
kind: Service
metadata:
  name: stock-app-service
spec:
  selector:
    app: stock-app
  type: LoadBalancer
  ports:
  - name: django
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: ema
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: rsi
    protocol: TCP
    port: 8082
    targetPort: 8082
  - name: macd
    protocol: TCP
    port: 8083
    targetPort: 8083
  - name: model
    protocol: TCP
    port: 8084
    targetPort: 8084
